### ISSUE TITLE
Minor thing (.name vs. .restaurantName)

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/map-dispatch-to-props-lab#2]
In restaurants.js, the line for displaying each entered Restaurant tries to reference restaurant.restaurantName, but it should be restaurant.name, and as a result nothing shows up in the Browser besides a bulletpoint. This doesn't actually affect the lab, but I thought it was worth pointing out.

`let restaurants = this.props.restaurants.map((restaurant, index) => <li key={index}>{restaurant.restaurantName}</li>);`

should be: 

`let restaurants = this.props.restaurants.map((restaurant, index) => <li key={index}>{restaurant.name}</li>);`

**Comment by gj** [comment]
Hi @DanL12186, mind making this change and submitting a PR?

**Comment by DanL12186** [comment]
Done

**Comment by gj** [comment]
Thanks @DanL12186 🙂
