### ISSUE TITLE
See my issue on previous lesson.

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/map-dispatch-to-props-lab#4]
Read https://stackoverflow.com/questions/34458261/how-to-get-simple-dispatch-from-this-props-using-connect-w-redux.

mapDispatchToProps is not always a needed pattern as it can be used implicitly.

**Comment by yehudamakarov** [comment]
The issue is that mention should be made about this because in other code, mapDispatchToProps may not be present and may lead to lots of confusion.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have updated this lab for mapDispatchToProps to allow for the different ways we can access dispatch in components.  We've also updated the previous readme and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
