### ISSUE TITLE
Solution Branch does not include function the lab explicitly asked us to write

### ISSUE THREAD

**Issue by emikojima** [learn-co-curriculum/map-dispatch-to-props-lab#5]
The instructions for this lab state:
Redux is already set up through index.js and the reducer manageRestaurants. Write a mapDispatchToProps() function that allows us to pass dispatched actions as props.

But there is not mapDispatchToProps() function in the solution branch. The solution branch offers the shortcut method, which we have not yet learned in the curriculum. 

Thank you!

**Comment by gac2117** [comment]
Yes, when I write a `mapDispatchToProps` function like the lab tells us to, the tests won't pass. The solution branch doesn't even have `mapDispatchToProps`...

**Comment by maxwellbenton** [comment]
Hi @emikojima,

Thank you for spotting this and providing feedback. We've updated the solution to use `mapDispatchToProps`, and kept the current solution as a commented out alternative.

We apologize for any frustration this may have caused, but thank you for contributing and
helping to improve this lesson!
